# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tvdb_party 0.8.0 ruby lib

Gem::Specification.new do |s|
  s.name = "p3-tvdb"
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jon Maddox", "Poul Hornsleth"]
  s.email = ["poulh@umich.edu"]
  s.homepage = "https://github.com/poulh/p3-tvdb"
  s.license       = "MIT"
  s.summary = "TVDB Search API"
  s.description = "Search thetvdb.com's database with this api ( requires thetvdb.com registration )"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files         = `git ls-files -z`.split("\x0")
  s.add_runtime_dependency "httparty", "~> 0.13.7"
end

